- ros_topic_name:  "/drone/motor_speed"
  gz_topic_name:   "/gazebo/command/motor_speed"
  ros_type_name:   "actuator_msgs/msg/Actuators"
  gz_type_name:    "gz.msgs.Actuators"
  direction:       "ROS_TO_GZ"
