- ros_topic_name:  "/drone/motor_speed"
  gz_topic_name:   "/gazebo/command/motor_speed"
  ros_type_name:   "actuator_msgs/msg/Actuators"
  gz_type_name:    "gz.msgs.Actuators"
  direction:       "ROS_TO_GZ"

#gz topic published by sensor plugin(sky_camera)
- ros_topic_name:  "/sky_cam/image_raw"
  gz_topic_name:   "/sky_cam"
  ros_type_name:   "sensor_msgs/msg/Image"
  gz_type_name:    "gz.msgs.Image"
  direction:       "GZ_TO_ROS"

#gz topic, muestra la posicion
- ros_topic_name: "/drone/pose"
  gz_topic_name: "/world/quadcopter/dynamic_pose/info"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: "GZ_TO_ROS"

#gz topic to ros2: LiDAR ToF sensor
- ros_topic_name: "/tof_sensor"
  gz_topic_name: "/tof_sensor"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: "GZ_TO_ROS"

#gz topic to ros2: IMU sensor
- ros_topic_name: "/IMU"
  gz_topic_name: "/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: "GZ_TO_ROS"